FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . .

RUN GOOS=linux \
    GOARCH=amd64 \
    CGO_ENABLED=0 \
    go build -ldflags "-s -w" -o bin/client-linux-amd64 cmd/client/main.go

# ---

FROM gcr.io/distroless/base-debian11

COPY --from=builder /app/bin/client-linux-amd64 /

USER nonroot:nonroot

ENTRYPOINT ["/client-linux-amd64"]
